version: "3"
services:
  server:
    container_name: server
    build: ./server
    volumes:
      - ./server:/usr/src/app/server
      - ./server/node_modules:/usr/src/app/server/node_modules
    ports:
      - "8081:8081"
  client:
    container_name: client
    build: ./client
    volumes:
      - ./client:/usr/src/app/client
      - ./client/node_modules:/usr/src/app/client/node_modules
    ports:
      - "8080:8080"
