version: "3"
services:
  server:
    container_name: server
    build: ./server
    volumes:
      - ./server:/usr/src/app/server
    ports:
      - "8081:8081"
  client:
    container_name: client
    build: ./client
    volumes:
      - ./client:/usr/src/app/client
    ports:
      - "8080:8080"
